name: Security audit

on:
    schedule:
        # Runs at 00:00 UTC everyday
        -   cron: '0 0 * * *'
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    pull_request:

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            # Ensure that the latest version of Cargo is installed
            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable
            -   uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
            -   uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

