name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:

    test:
        name: Test Suite
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable
            -   uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
            -   name: Run tests
                run: cargo test --all-features --workspace

    rustfmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable
                with:
                    components: rustfmt
            -   uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
            -   name: Check formatting
                run: cargo fmt --all --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable
                with:
                    components: clippy
            -   uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
            -   name: Clippy check
                run: cargo clippy --all-targets --all-features --workspace -- -D warnings

    docs:
        name: Docs
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable
            -   uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
            -   name: Check documentation
                env:
                    RUSTDOCFLAGS: -D warnings
                run: cargo doc --no-deps --document-private-items --all-features --workspace --examples

